eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8100
spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/users
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    security:
      jwt:
        secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
        expire-length: 3600000

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D